### ISSUE TITLE
Code example of using the pre-trained model

### ISSUE THREAD

**Issue by MiladAlshomary** [tuhinjubcse/AMPERSAND-EMNLP2019#1]
Hi,

I came across your work on argument mining! Could you please provide an example on how to use the pre-trained model to extract claims, premise from text?

Thanks,

**Comment by tuhinjubcse** [comment]
https://drive.google.com/file/d/1nc0A4C7RTGnDpsDtP3UwddXoOIRT_06-/view?usp=sharing

Can you download this code and use 
This is older version of hugging face

**Comment by MiladAlshomary** [comment]
Thanks a lot. I will take a look at it.
